-- CREATE DATABASE productsdb IF NOT EXISTS;

-- use productsdb;

-- CREATE TABLE product(
-- id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
-- name VARCHAR(255) NOT NULL UNIQUE,
-- description VARCHAR(400) NOT NULL,
-- price DECIMAL,
-- createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- )
-- describe product;


-- VARCHAR ALMACENA STRINGS CON UNA LONGITUD MAXIMA DADA
-- CHAR  ALMANEA STRINGS CON UNA LONGITUD ESPECIFICA, NI MAS NI MENOS
-- TEXT ALMECENA STRING SIN UNA LONGITUD ESPECIFICA 
-- TIMESTAMP DEFAULT CURRENT_TIMESTAMP AGREGA LA FECHA Y HORA EXACTA

